listening-port=3478
listening-ip=0.0.0.0
external-ip=2.26.8.168
realm=finchgram.ru
lt-cred-mech
min-port=50000
max-port=50050
max-bps=3000000
bps-capacity=0
total-quota=100
stale-nonce=600
channel-lifetime=600
permission-lifetime=300
verbose
log-file=stdout
no-cli
tls-listening-port=5349
cert=/certs/server.crt
pkey=/certs/server.key
allow-loopback-peers
